stairs( u1, 'm');
hold on;
stairs( u2, 'r');
stairs( u3, 'b');
stairs( u4, 'c');
% stairs( u5, 'y');
% stairs( u6, 'k');
% stairs( u7, 'g');
title('Porównanie sygna³u steruj¹cego dla ró¿nych horyzontów sterowania');
% legend('l = 0', 'l = 1', 'l = 5', 'l = 20', 'l = 50', 'l = 100', 'l = 500', 'Location', 'best');
legend('Nu = 16', 'Nu = 3', 'Nu = 2', 'Nu = 1', 'Location', 'best');
xlabel('k');
ylabel('u(k)');
%saveas(gcf,'picture/por_Nu_u.png');
hold off;

figure;
stairs( y1, 'm');
hold on;
stairs( y2, 'r');
stairs( y3, 'b');
stairs( y4, 'c');
% stairs( y5, 'y');
% stairs( y6, 'k');
% stairs( y7, 'g');
title('Porównanie wyjœcia modelu dla ró¿nych horyzontów sterowania');
% legend('N = 70', 'N = 20', 'N = 16', 'N = 15', 'N = 14', 'N = 13', 'N = 12', 'Location', 'North');
legend('Nu = 16', 'Nu = 3', 'Nu = 2', 'Nu = 1', 'Location', 'best');
% legend('l = 0', 'l = 1', 'l = 5', 'l = 20', 'l = 50', 'l = 100', 'l = 500', 'Location', 'best');
xlabel('k');
ylabel('y(k)');
%saveas(gcf,'picture/por_Nu_y.png');
hold off;
